### PR TITLE
speedtest implemented

### PR DESCRIPTION
**Pull request by moopie**

### CODE REVIEW

**Comment by anlutro** [comment]
I lol'd. amend the commit to get rid of the .idea crap and I'll merge

**Comment by moopie** [comment]
pycharm creates it automatically

are you discriminating against pycharm users?

**Comment by anlutro** [comment]
So you *manually* added it to .gitignore? That's even worse.

Here's what you should do:

```
# ~/.gitconfig
[core]
excludesfile = ~/.gitignore_global

# ~/.gitignore_global
.idea
```

**Comment by moopie** [comment]
this is what happens when the nazism controls the botologist,

fine fine

**Comment by anlutro** [comment]
Couldn't amend the commit eh? Well, whatever

**Comment by moopie** [comment]
yeah well w/e

**Pull request merged**
