### PR TITLE
Dota, wew

### PR DESCRIPTION
**Pull request by x89**

### CODE REVIEW

**Comment by anlutro** [comment]
WTF is with all these unrelated commits?

Re-commit the dota plugin on a new branch based on master and I'll merge it

**Comment by moopie** [comment]
@anlutro this is how dictatorship looks like

**Comment by x89** [comment]
Pls @anlutro

**Comment by anlutro** [comment]
Only use ASCII in the YAML config, please.

There's a `requirements.txt` in the root directory, use that one.

Get that `*.swp` out of the gitignore. It belongs in your [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

22 commits WTF? Squash them please.

**Comment by anlutro** [comment]
Also can't we make a way for people to assign DOTA IDs to names through an IRC command? Hard-coding it in the plugin module is the worst possible solution.

**Comment by x89** [comment]
Why only ASCII in the YAML example?

Requirements is gone, idk how that got there and you have a point on the `*.swp`, I'll take that out.

Why squash the commits? They're history!

And the reason for not implementing dynamic Dota IDs is because a proper backing storage for that would be a database, which is beyond the scope of what's necessary for 2-3 players. I could compromise and put it into the config file as well but that's a very half-way measure.

**Comment by anlutro** [comment]
History is nice but in your case it's just useless noise. Like this one https://github.com/anlutro/botologist/pull/69/commits/39b66d58156b4cbb13bdaf14d33371c4f3569d12

Certain YAML loaders only accept ASCII for compatibility reasons.. Same reason as only using ASCII in python source files I suppose. But on the other hand, IRC channel names allow unicode characters, which means you'd have to put unicode characters into the YAML anyway, so never mind that.

**Comment by anlutro** [comment]
You could do what I've done with the streams plugin, just write a simple state to a JSON file. A proper database (redis or something) would obviously be better but a file works fine.

**Pull request closed without merging**
